### ISSUE TITLE
I really don't understand setup

### ISSUE THREAD

**Issue by mrhappyma** [fourjr/modmail-plugins#13]
All my emojis are "invalid", and when I try to set a channel it doesn't work. Help me please!

**Comment by mrhappyma** [comment]
^note- emoji suggestions plugin

**Comment by fourjr** [comment]
Hey, this plugin was made specifically for the Modmail discord server. The options are configurable however I do not provide support for this plugin, sorry.

**Comment by mrhappyma** [comment]
*poop emoji*
