### ISSUE TITLE
Not able to find member count variable.

### ISSUE THREAD

**Issue by Bobinatorxl** [fourjr/modmail-plugins#15]
Hello, I am trying to have my welcome message kinda look like this:
![image](https://user-images.githubusercontent.com/69617777/91934820-1e45c480-eca1-11ea-87e1-b451c5e3e5b9.png)
but I can't find the variable for member count. Is there one, if not I think adding that would help a lot, thanks.

**Comment by fourjr** [comment]
Hi, please use `{guild.member_count}`

**Comment by Bobinatorxl** [comment]
I got it to work, thank you for your help, enjoy your day :)
